# RX

El código de Matlab traducido a Python

Aquí en el primer bloque verás que están las mismas variables que pusiste tú pero que el array lo inicializo con valores. Son los que me aparecían en Matlab con la opción de default y los he dejado así para no liarme y poder comprobar fácilmente que las operaciones eran correctas.

In [ ]:
import numpy

%run inversa.ipynb
%run covarianza.ipynb
%run deviacion.ipynb
%run media.ipynb

N = 8  # bandas
M = 32  # pixeles
if False:
    X = array([[209, 246, 108, 174, 71, 113, 182, 246, 229, 209, 91, 98, 146, 43, 59, 28, 67, 223, 103, 232, 200, 148, 167, 176, 125, 165, 160, 58, 232, 155, 22, 61],
            [232, 248, 235, 194, 12, 98, 194, 88, 246, 63, 213, 146, 121, 155, 234, 247, 205, 149, 20, 242, 100, 16, 188, 47, 112, 97, 151, 44, 251, 183, 68, 118],
            [33, 41, 203, 191, 25, 196, 71, 150, 141, 238, 150, 20, 4, 68, 40, 2, 111, 141, 62, 126, 62, 61, 166, 95, 115, 208, 54, 59, 113, 57, 206, 247],
            [234, 249, 246, 101, 211, 204, 175, 58, 36, 90, 141, 14, 87, 168, 212, 199, 234, 38, 32, 126, 104, 91, 116, 161, 79, 137, 78, 112, 29, 31, 8, 140],
            [162, 246, 168, 168, 178, 48, 168, 193, 39, 51, 235, 136, 42, 177, 138, 210, 47, 219, 48, 87, 25, 211, 141, 200, 131, 90, 121, 80, 67, 76, 238, 134],
            [25, 125, 10, 44, 82, 126, 42, 66, 66, 65, 74, 200, 204, 192, 256, 223, 68, 160, 62, 231, 34, 4, 76, 21, 131, 241, 60, 237, 105, 82, 187, 60],
            [72, 205, 218, 181, 244, 115, 31, 130, 216, 158, 194, 240, 80, 116, 21, 22, 38, 90, 107, 95, 242, 12, 191, 238, 210, 225, 217, 111, 153, 109, 126, 126],
            [141, 37, 240, 9, 9, 166, 128, 179, 66, 122, 193, 34, 136, 22, 114, 103, 35, 132, 13, 29, 245, 44, 49, 199, 204, 141, 50, 48, 68, 131, 149, 160]])
    check = True
else:
    X = numpy.random.randint(low = 0, high = 256, size=(N, M))
    check = False
X = X.astype('float64')

In [ ]:
media = media(X)
deviacion = deviacion(X, media)
covarianza = covarianza(X, deviacion)
inversa_cov = inversa(covarianza)

## El resto (para probar que funciona)

In [ ]:
R = numpy.zeros([M], numpy.longdouble)

for i in range(M):
    resta = subtract(X[:, i], media)  # resta la columna
    t = resta.reshape((1, -1)) # otro transpose
    R[i]=(matmul(matmul(t, inversa_cov), resta))

In [ ]:
control = array([[6.98255846], [12.93698463], [10.34438199], [6.71785252], [12.91176259], [7.05938212], [4.85671939], [6.74011743], [7.54006757], [6.94963658], [6.55902276], [9.07915113], [7.04155694], [3.9978728], [7.44125174], [8.84686045], [10.02591519], [7.78372555], [8.07804037], [8.51903075], [11.17111338], [12.58061393], [2.88643314], [7.30410476], [3.66816483], [10.26784811], [3.65019396], [6.04739986], [5.7849899], [5.24184292], [12.38433902], [6.60106522]])

if check:
    assert numpy.allclose(R, control[:, 0]), "Uh oh"

print("Todo ok")

In [ ]:
R

In [ ]:
# Control
"""
[array([6.98255846]),
 array([12.93698463]),
 array([10.34438199]),
 array([6.71785252]),
 array([12.91176259]),
 array([7.05938212]),
 array([4.85671939]),
 array([6.74011743]),
 array([7.54006757]),
 array([6.94963658]),
 array([6.55902276]),
 array([9.07915113]),
 array([7.04155694]),
 array([3.9978728]),
 array([7.44125174]),
 array([8.84686045]),
 array([10.02591519]),
 array([7.78372555]),
 array([8.07804037]),
 array([8.51903075]),
 array([11.17111338]),
 array([12.58061393]),
 array([2.88643314]),
 array([7.30410476]),
 array([3.66816483]),
 array([10.26784811]),
 array([3.65019396]),
 array([6.04739986]),
 array([5.7849899]),
 array([5.24184292]),
 array([12.38433902]),
 array([6.60106522])]
 """